apiVersion: apps/v1
kind: Deployment
metadata:
  name: policyclaim-api
  namespace: policyclaim
spec:
  replicas: 2
  selector:
    matchLabels:
      app: policyclaim-api
  template:
    metadata:
      labels:
        app: policyclaim-api
    spec:
      containers:
        - name: api
          image: policyclaimregistry.azurecr.io/policyclaim-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: AI_SERVICE_BASE_URL
              value: http://policyclaim-ai-service:8000
---
apiVersion: v1
kind: Service
metadata:
  name: policyclaim-api
  namespace: policyclaim
spec:
  selector:
    app: policyclaim-api
  ports:
    - port: 8080
      targetPort: 8080
